services:
  - type: web
    name: backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start

  - type: web
    name: frontend
    env: static
    plan: free
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
